services:
  - type: web
    name: paxlogistic
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://pax-logistic.onrender.com
      - key: VITE_APP_MODE
        value: admin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
